name: Create EC2 Instance

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        description: "Instance name"
      ami:
        required: true
        description: "AMI ID"
      instance_type:
        required: true
        default: "t2.micro"
        description: "Instance type"
      region:
        required: true
        default: "ap-southeast-2"
        description: "AWS region"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/ec2

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/ec2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_name: ${{ github.event.inputs.name }}
          TF_VAR_ami: ${{ github.event.inputs.ami }}
          TF_VAR_instance_type: ${{ github.event.inputs.instance_type }}
          TF_VAR_region: ${{ github.event.inputs.region }}
